# Sidebar navigation

#- label: 'Introduction'
#  link: '/'
#- label: 'Getting started'
#  link: '/getting-started'
#- label: Usage
#  items:
#    - label: 'Creating docs'
#      link: '/usage/creating-docs'
#    - label: 'Navigation'
#      link: '/usage/navigation'
#    - label: 'Shadowing'
#      link: '/usage/shadowing'


- label: 'Network Basics'
  link: '/1-network-basics'
- label: 'Cabling'
  link: '/2-cabling'
- label: 'IP Addressing'
  link: '/3-ip-addressing'
- label: 'Network Tools'
  link: '/4-network-tools'
- label: 'Network Protocols'
  link: '/5-network-protocols'
- label: 'Cisco IOS'
  link: '/6-cisco-ios'
- label: 'IP Routing'
  link: '/7-ip-routing'
- label: 'RIP'
  link: '/8-rip'
- label: 'EIGRP'
  link: '/9-eigrp'
- label: 'OSPF'
  link: '/10-ospf'
- label: 'LAN Switching'
  link: '/11-lan-switching'
- label: 'VLAN'
  link: '/12-vlan'
- label: 'VTP'
  link: '/13-vtp'
- label: 'STP and RSTP'
  link: '/14-stp-and-rstp'
- label: 'ACLs'
  link: '/15-acls'
- label: 'NAT'
  link: '/16-nat'
- label: 'IPv6'
  link: '/17-ipv6'
- label: 'Misc'
  link: '/18-misc'